// Imports the wall's kids-UI handoff into the app and regenerates the Dart
// sources derived from it.
//
// Usage (run from mobile/):
//   dart run tool/sync_kids_assets.dart                  # sync + regenerate
//   dart run tool/sync_kids_assets.dart --source=<dir>   # non-default handoff
//   dart run tool/sync_kids_assets.dart --check          # verify HASHES only
//
// Reads  <source>/{tokens.json, pictos-manifest.json, resolve-fixtures.json,
//                  pictos/{light,dark}/*.svg}
// Writes assets/kids/{tokens.json, pictos-manifest.json, pictos/**}
//        assets/kids/HASHES.sha256            (diff this after a regeneration)
//        test/fixtures/resolve-fixtures.json  (test-only, not a bundle asset)
//        lib/kids/kid_tokens.g.dart           (KidTokens ThemeExtension)
//        lib/kids/picto_catalog.g.dart        (motif names/categories/labels)
//
// Pure Dart on purpose: no packages, so it runs anywhere `dart` does.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

const String _defaultSource = '../docs/kids-ui/handoff';
const String _assetsDir = 'assets/kids';
const String _fixturesOut = 'test/fixtures/resolve-fixtures.json';
const String _tokensOut = 'lib/kids/kid_tokens.g.dart';
const String _catalogOut = 'lib/kids/picto_catalog.g.dart';
const String _header =
    '// GENERATED CODE - DO NOT MODIFY BY HAND.\n'
    '// Generated by tool/sync_kids_assets.dart from the wall handoff.\n'
    '// Re-run: dart run tool/sync_kids_assets.dart\n';
const List<String> _themes = <String>['light', 'dark'];

Future<void> main(List<String> args) async {
  String source = _defaultSource;
  bool check = false;
  for (final String arg in args) {
    if (arg == '--check') {
      check = true;
    } else if (arg.startsWith('--source=')) {
      source = arg.substring('--source='.length);
    } else {
      stderr.writeln('Unknown argument: $arg');
      exit(64);
    }
  }

  if (!Directory('lib').existsSync()) {
    stderr.writeln('Run from mobile/.');
    exit(2);
  }

  if (check) {
    exit(_verifyHashes() ? 0 : 1);
  }

  final Directory src = Directory(source);
  if (!src.existsSync()) {
    stderr.writeln('Handoff directory not found: $source');
    exit(2);
  }

  final List<String> failures = <String>[];
  for (final String f in <String>[
    'tokens.json',
    'pictos-manifest.json',
    'resolve-fixtures.json',
  ]) {
    if (!File('$source/$f').existsSync()) {
      failures.add('missing $source/$f');
    }
  }
  for (final String theme in _themes) {
    if (!Directory('$source/pictos/$theme').existsSync()) {
      failures.add('missing $source/pictos/$theme');
    }
  }
  if (failures.isNotEmpty) {
    failures.forEach(stderr.writeln);
    exit(2);
  }

  final Directory assets = Directory(_assetsDir);
  if (assets.existsSync()) {
    assets.deleteSync(recursive: true);
  }
  assets.createSync(recursive: true);

  _copy('$source/tokens.json', '$_assetsDir/tokens.json');
  _copy('$source/pictos-manifest.json', '$_assetsDir/pictos-manifest.json');
  for (final String theme in _themes) {
    final List<File> svgs =
        Directory('$source/pictos/$theme')
            .listSync()
            .whereType<File>()
            .where((File f) => f.path.endsWith('.svg'))
            .toList()
          ..sort((File a, File b) => a.path.compareTo(b.path));
    for (final File svg in svgs) {
      _copy(svg.path, '$_assetsDir/pictos/$theme/${_basename(svg.path)}');
    }
  }
  Directory(_fixturesOut).parent.createSync(recursive: true);
  _copy('$source/resolve-fixtures.json', _fixturesOut);

  _writeHashes();

  final Map<String, Object?> tokens = _readJson('$_assetsDir/tokens.json');
  final Map<String, Object?> manifest = _readJson(
    '$_assetsDir/pictos-manifest.json',
  );
  File(_tokensOut).writeAsStringSync(_generateTokens(tokens));
  File(_catalogOut).writeAsStringSync(_generateCatalog(manifest));

  final ProcessResult fmt = Process.runSync('dart', <String>[
    'format',
    _tokensOut,
    _catalogOut,
  ]);
  if (fmt.exitCode != 0) {
    stderr.writeln(fmt.stderr);
    exit(1);
  }

  final int svgCount = Directory(
    '$_assetsDir/pictos',
  ).listSync(recursive: true).whereType<File>().length;
  stdout.writeln(
    'OK: $svgCount SVGs, tokens, manifest, fixtures synced; '
    'HASHES.sha256 + generated sources written.',
  );
}

void _copy(String from, String to) {
  File(to)
    ..createSync(recursive: true)
    ..writeAsBytesSync(File(from).readAsBytesSync());
}

String _basename(String path) => path.substring(path.lastIndexOf('/') + 1);

Map<String, Object?> _readJson(String path) =>
    (jsonDecode(File(path).readAsStringSync()) as Map<Object?, Object?>)
        .cast<String, Object?>();

// --- hashes -----------------------------------------------------------------

List<String> _assetFiles() {
  final List<String> paths =
      Directory(_assetsDir)
          .listSync(recursive: true)
          .whereType<File>()
          .map((File f) => f.path.substring(_assetsDir.length + 1))
          .where((String p) => p != 'HASHES.sha256')
          .toList()
        ..sort();
  return paths;
}

String _hashLines() {
  final StringBuffer out = StringBuffer();
  for (final String rel in _assetFiles()) {
    final String digest = sha256Hex(File('$_assetsDir/$rel').readAsBytesSync());
    out.writeln('$digest  $rel');
  }
  return out.toString();
}

void _writeHashes() {
  File('$_assetsDir/HASHES.sha256').writeAsStringSync(_hashLines());
}

bool _verifyHashes() {
  final File file = File('$_assetsDir/HASHES.sha256');
  if (!file.existsSync()) {
    stderr.writeln('$_assetsDir/HASHES.sha256 missing.');
    return false;
  }
  if (file.readAsStringSync() != _hashLines()) {
    stderr.writeln('Assets differ from HASHES.sha256 - re-run the sync.');
    return false;
  }
  stdout.writeln('OK: ${_assetFiles().length} files match HASHES.sha256.');
  return true;
}

// --- generators -------------------------------------------------------------

String _camel(String kebab) {
  final List<String> parts = kebab.split('-');
  return parts.first +
      parts
          .skip(1)
          .map((String p) => p[0].toUpperCase() + p.substring(1))
          .join();
}

String _color(String hex) {
  final String h = hex.replaceFirst('#', '').toUpperCase();
  if (h.length != 6) {
    throw FormatException('Expected #RRGGBB, got $hex');
  }
  return 'Color(0xFF$h)';
}

String _str(String value) {
  final String escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
  return "'$escaped'";
}

String _generateTokens(Map<String, Object?> json) {
  final Map<String, Object?> tokens = (json['tokens']! as Map<Object?, Object?>)
      .cast<String, Object?>();
  final List<String> names = tokens.keys.toList();
  final List<String> accents = names
      .where(
        (String n) =>
            n.startsWith('accent-') &&
            !n.endsWith('-tint') &&
            !n.endsWith('-ink'),
      )
      .map((String n) => n.substring('accent-'.length))
      .toList();

  String valueOf(String token, String theme) =>
      ((tokens[token]! as Map<Object?, Object?>)[theme]! as String);

  final StringBuffer b = StringBuffer()
    ..writeln(_header)
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln()
    ..writeln('/// Three tones of one member colour (R1.2).')
    ..writeln('@immutable')
    ..writeln('class KidAccent {')
    ..writeln('  const KidAccent({')
    ..writeln('    required this.base,')
    ..writeln('    required this.tint,')
    ..writeln('    required this.ink,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  /// Ring, progress, check and the filled "done" card.')
    ..writeln('  final Color base;')
    ..writeln()
    ..writeln('  /// Soft large surfaces: column, picto tile.')
    ..writeln('  final Color tint;')
    ..writeln()
    ..writeln('  /// Text and icons on [tint] (contrast >= 4.5:1).')
    ..writeln('  final Color ink;')
    ..writeln('}')
    ..writeln()
    ..writeln(
      '/// All ${names.length} design tokens of the wall (`tokens.json`), '
      'light + dark.',
    )
    ..writeln('///')
    ..writeln(
      '/// The only source of colour for kid-facing widgets (R1.1): '
      'read it via',
    )
    ..writeln('/// `context.kid`, never write hex in widget code.')
    ..writeln('@immutable')
    ..writeln('class KidTokens extends ThemeExtension<KidTokens> {')
    ..writeln('  const KidTokens({');
  for (final String n in names) {
    b.writeln('    required this.${_camel(n)},');
  }
  b
    ..writeln('  });')
    ..writeln();
  for (final String n in names) {
    b.writeln('  final Color ${_camel(n)};');
  }
  for (final String theme in _themes) {
    b
      ..writeln()
      ..writeln('  static const KidTokens $theme = KidTokens(');
    for (final String n in names) {
      b.writeln('    ${_camel(n)}: ${_color(valueOf(n, theme))},');
    }
    b.writeln('  );');
  }
  b
    ..writeln()
    ..writeln('  /// The 8 member-colour names, in wall order.')
    ..writeln(
      '  static const List<String> accentNames = <String>[${accents.map(_str).join(', ')}];',
    )
    ..writeln()
    ..writeln(
      '  /// Resolves a member colour name; unknown or null falls back '
      'to sky,',
    )
    ..writeln('  /// matching `AccentPalette.fallback`.')
    ..writeln('  KidAccent accent(String? name) {')
    ..writeln('    switch (name?.toLowerCase()) {');
  for (final String a in accents.where((String a) => a != 'sky')) {
    b
      ..writeln('      case ${_str(a)}:')
      ..writeln('        return KidAccent(')
      ..writeln('          base: accent${_camel('-$a')},')
      ..writeln('          tint: accent${_camel('-$a')}Tint,')
      ..writeln('          ink: accent${_camel('-$a')}Ink,')
      ..writeln('        );');
  }
  b
    ..writeln('      default:')
    ..writeln('        return KidAccent(')
    ..writeln('          base: accentSky,')
    ..writeln('          tint: accentSkyTint,')
    ..writeln('          ink: accentSkyInk,')
    ..writeln('        );')
    ..writeln('    }')
    ..writeln('  }')
    ..writeln()
    ..writeln(
      '  /// Every token keyed by its `tokens.json` name (`accent-peach-tint`).',
    )
    ..writeln('  Map<String, Color> asMap() => <String, Color>{');
  for (final String n in names) {
    b.writeln('    ${_str(n)}: ${_camel(n)},');
  }
  b
    ..writeln('  };')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  KidTokens copyWith({');
  for (final String n in names) {
    b.writeln('    Color? ${_camel(n)},');
  }
  b
    ..writeln('  }) {')
    ..writeln('    return KidTokens(');
  for (final String n in names) {
    b.writeln('      ${_camel(n)}: ${_camel(n)} ?? this.${_camel(n)},');
  }
  b
    ..writeln('    );')
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  KidTokens lerp(ThemeExtension<KidTokens>? other, double t) {')
    ..writeln('    if (other is! KidTokens) {')
    ..writeln('      return this;')
    ..writeln('    }')
    ..writeln('    return KidTokens(');
  for (final String n in names) {
    final String f = _camel(n);
    b.writeln('      $f: Color.lerp($f, other.$f, t)!,');
  }
  b
    ..writeln('    );')
    ..writeln('  }')
    ..writeln('}');
  return b.toString();
}

String _generateCatalog(Map<String, Object?> manifest) {
  final List<Map<String, Object?>> pictos =
      (manifest['pictos']! as List<Object?>)
          .map(
            (Object? e) =>
                (e! as Map<Object?, Object?>).cast<String, Object?>(),
          )
          .toList();
  final Set<String> categories = <String>{
    for (final Map<String, Object?> p in pictos) p['category']! as String,
  };

  final StringBuffer b = StringBuffer()
    ..writeln(_header)
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln(
      '/// Motif categories (R3.2): task cards show only `task`, '
      'events only `event`.',
    )
    ..writeln('enum PictoCategory { ${categories.join(', ')} }')
    ..writeln()
    ..writeln('/// One motif of the wall\'s picto registry.')
    ..writeln('class PictoMeta {')
    ..writeln('  const PictoMeta({')
    ..writeln('    required this.name,')
    ..writeln('    required this.category,')
    ..writeln('    required this.emoji,')
    ..writeln('    required this.labels,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  /// Kebab-case motif name, also the SVG file name.')
    ..writeln('  final String name;')
    ..writeln('  final PictoCategory category;')
    ..writeln()
    ..writeln('  /// Canonical emoji stored in `Chore.icon` (R3.3).')
    ..writeln('  final String emoji;')
    ..writeln()
    ..writeln('  /// Localised label by language code (de, en, fr, it).')
    ..writeln('  final Map<String, String> labels;')
    ..writeln('}')
    ..writeln()
    ..writeln(
      'const Map<String, PictoMeta> kPictoCatalog = <String, PictoMeta>{',
    );
  for (final Map<String, Object?> p in pictos) {
    final Map<String, Object?> labels = (p['labels']! as Map<Object?, Object?>)
        .cast<String, Object?>();
    b
      ..writeln('  ${_str(p['name']! as String)}: PictoMeta(')
      ..writeln('    name: ${_str(p['name']! as String)},')
      ..writeln('    category: PictoCategory.${p['category']},')
      ..writeln('    emoji: ${_str(p['emoji']! as String)},')
      ..writeln('    labels: <String, String>{');
    for (final MapEntry<String, Object?> l in labels.entries) {
      b.writeln('      ${_str(l.key)}: ${_str(l.value! as String)},');
    }
    b
      ..writeln('    },')
      ..writeln('  ),');
  }
  b.writeln('};');
  return b.toString();
}

// --- SHA-256 (FIPS 180-4) ---------------------------------------------------

const List<int> _k = <int>[
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, //
  0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
  0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
  0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
  0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
  0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
  0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
  0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
  0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
];

int _rotr(int x, int n) => ((x >> n) | (x << (32 - n))) & 0xffffffff;

String sha256Hex(Uint8List data) {
  final int bitLength = data.length * 8;
  final int paddedLength = ((data.length + 9 + 63) ~/ 64) * 64;
  final Uint8List msg = Uint8List(paddedLength)..setRange(0, data.length, data);
  msg[data.length] = 0x80;
  final ByteData view = ByteData.view(msg.buffer);
  view.setUint32(paddedLength - 8, bitLength ~/ 0x100000000);
  view.setUint32(paddedLength - 4, bitLength & 0xffffffff);

  final List<int> h = <int>[
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, //
    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
  ];
  final List<int> w = List<int>.filled(64, 0);
  for (int off = 0; off < paddedLength; off += 64) {
    for (int i = 0; i < 16; i++) {
      w[i] = view.getUint32(off + i * 4);
    }
    for (int i = 16; i < 64; i++) {
      final int s0 =
          _rotr(w[i - 15], 7) ^ _rotr(w[i - 15], 18) ^ (w[i - 15] >> 3);
      final int s1 =
          _rotr(w[i - 2], 17) ^ _rotr(w[i - 2], 19) ^ (w[i - 2] >> 10);
      w[i] = (w[i - 16] + s0 + w[i - 7] + s1) & 0xffffffff;
    }
    int a = h[0], b = h[1], c = h[2], d = h[3];
    int e = h[4], f = h[5], g = h[6], hh = h[7];
    for (int i = 0; i < 64; i++) {
      final int s1 = _rotr(e, 6) ^ _rotr(e, 11) ^ _rotr(e, 25);
      final int ch = (e & f) ^ ((~e & 0xffffffff) & g);
      final int t1 = (hh + s1 + ch + _k[i] + w[i]) & 0xffffffff;
      final int s0 = _rotr(a, 2) ^ _rotr(a, 13) ^ _rotr(a, 22);
      final int maj = (a & b) ^ (a & c) ^ (b & c);
      final int t2 = (s0 + maj) & 0xffffffff;
      hh = g;
      g = f;
      f = e;
      e = (d + t1) & 0xffffffff;
      d = c;
      c = b;
      b = a;
      a = (t1 + t2) & 0xffffffff;
    }
    h[0] = (h[0] + a) & 0xffffffff;
    h[1] = (h[1] + b) & 0xffffffff;
    h[2] = (h[2] + c) & 0xffffffff;
    h[3] = (h[3] + d) & 0xffffffff;
    h[4] = (h[4] + e) & 0xffffffff;
    h[5] = (h[5] + f) & 0xffffffff;
    h[6] = (h[6] + g) & 0xffffffff;
    h[7] = (h[7] + hh) & 0xffffffff;
  }
  return h.map((int v) => v.toRadixString(16).padLeft(8, '0')).join();
}
