/// Emoji table ported 1:1 from `src/components/pictos/emoji-map.ts`
/// (`TABLE`). Emoji are stored without variation selectors or skin tones.
/// Row order is the priority when an emoji appears in several rows.
library;

const List<(String, List<String>)> kEmojiTable = <(String, List<String>)>[
  ('water', <String>['💧', '🚰', '🥤', '🫗', '🥛', '🧊', '🍶']),
  ('teeth', <String>['🪥', '🦷']),
  ('tidy-toys', <String>['🧸', '🪀', '🧩', '🪆', '🚂', '🎲']),
  (
    'get-dressed',
    <String>['👕', '👚', '👗', '👖', '🧦', '🧥', '👔', '🩳', '🧤', '🧣'],
  ),
  ('make-bed', <String>['🛏']),
  ('set-table', <String>['🍽', '🥢']),
  ('feed-dog', <String>['🐶', '🐕', '🦮', '🐩', '🦴', '🐕‍🦺']),
  ('feed-cat', <String>['🐱', '🐈', '🐈‍⬛', '🐟', '🐠', '🐹', '🐰', '🐇']),
  ('trash', <String>['🚮', '🗑', '♻', '🚯']),
  ('water-plants', <String>['🌱', '🪴', '🌻', '🌷', '🌿', '🌼', '🌸', '🌵']),
  ('homework', <String>['✏', '📚', '📝', '✍', '🖊', '📐', '🖋', '📏', '🧮']),
  ('read', <String>['📖', '📕', '📗', '📘', '📙', '📚']),
  ('laundry', <String>['🧺', '👙']),
  ('wash-clothes', <String>['🫧', '🧺']),
  ('dishes', <String>['🧽', '🫙']),
  ('wash-hands', <String>['🧼', '👐', '🙌', '🤲', '🫧']),
  ('bath', <String>['🛁', '🚿', '🛀', '🦆', '🧴']),
  ('pajamas', <String>['🛌', '😴', '💤', '🥱']),
  ('backpack', <String>['🎒']),
  ('sweep', <String>['🧹']),
  ('vacuum', <String>['🌪', '💨']),
  (
    'breakfast',
    <String>[
      '🥣',
      '🍳',
      '🥐',
      '🍞',
      '🥞',
      '🍎',
      '🍌',
      '🥪',
      '🥄',
      '🧇',
      '🍓',
      '🍏',
    ],
  ),
  ('medicine', <String>['💊', '💉', '🌡', '🤒', '🧪']),
  (
    'music',
    <String>['🎹', '🎵', '🎶', '🎼', '🪈', '🎺', '🥁', '🎻', '🪗', '🪘'],
  ),
  ('tidy-room', <String>['🗄', '🚪', '🛋', '🪑', '🏠', '🏡']),
  ('shoes', <String>['👟', '👞', '🥾', '👢', '🩴', '👠', '🥿']),
  ('shopping', <String>['🛒', '🛍', '🧾', '🏪']),
  ('tod-morning', <String>['🌅', '🌄', '🐓']),
  ('tod-day', <String>['☀', '🌞', '🌤']),
  ('tod-evening', <String>['🌙', '🌃', '🌌']),
  ('tod-night', <String>['🌛', '🌜', '🌚', '💤']),
  ('tod-anytime', <String>['🌗', '🌓', '🕒', '⏰', '🕐', '⌚', '⏱', '🕰']),
  ('celebrate', <String>['🏆', '🎉', '🥳', '🎊', '🏅', '🥇']),
  ('oops', <String>['🩹']),
  ('relax', <String>['🏖', '⛱', '🧘', '😌']),
  ('star', <String>['⭐', '🌟', '✨', '💫']),
  ('undo', <String>['↩', '↶', '🔙']),
  ('next', <String>['👉', '➡', '▶']),
  ('pause', <String>['⏳', '⌛', '⏸']),
  ('event-school', <String>['🏫', '🧑‍🏫', '👩‍🏫', '👨‍🏫', '🎓', '📚', '✏']),
  ('event-kindergarten', <String>['🖍', '🧱', '🎨', '🖌', '✂']),
  ('event-soccer', <String>['⚽', '🥅']),
  ('event-swim', <String>['🏊', '🩱', '🤿', '🥽']),
  (
    'event-doctor',
    <String>['🩺', '🏥', '🧑‍⚕', '👩‍⚕', '👨‍⚕', '🚑', '🦷', '💊', '💉'],
  ),
  ('event-birthday', <String>['🎂', '🎁', '🎈', '🧁', '🍰']),
  (
    'event-dinner',
    <String>[
      '🍲',
      '🍝',
      '🍕',
      '🥘',
      '🍛',
      '🍜',
      '🍴',
      '🥗',
      '🍖',
      '🍗',
      '🍽',
      '🍳',
      '🥐',
      '🥞',
    ],
  ),
  (
    'event-music',
    <String>[
      '🎸',
      '🎤',
      '🎷',
      '🎙',
      '🎧',
      '🎹',
      '🎵',
      '🎶',
      '🎼',
      '🎻',
      '🥁',
      '🪈',
      '🎺',
      '🪗',
    ],
  ),
  (
    'event-play',
    <String>['🪣', '🛝', '🪁', '🏐', '🏀', '🎠', '🤸', '🧸', '🧩'],
  ),
  (
    'event-trip',
    <String>[
      '🚗',
      '🚙',
      '🚌',
      '🚆',
      '✈',
      '🏔',
      '⛰',
      '🧳',
      '🏕',
      '🗺',
      '🚂',
      '⛵',
      '🦁',
      '🐘',
    ],
  ),
  ('event-bike', <String>['🚲', '🚴', '🛴', '🛹', '🚵']),
];
