// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by tool/sync_kids_assets.dart from the wall handoff.
// Re-run: dart run tool/sync_kids_assets.dart

// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

/// Three tones of one member colour (R1.2).
@immutable
class KidAccent {
  const KidAccent({required this.base, required this.tint, required this.ink});

  /// Ring, progress, check and the filled "done" card.
  final Color base;

  /// Soft large surfaces: column, picto tile.
  final Color tint;

  /// Text and icons on [tint] (contrast >= 4.5:1).
  final Color ink;
}

/// All 62 design tokens of the wall (`tokens.json`), light + dark.
///
/// The only source of colour for kid-facing widgets (R1.1): read it via
/// `context.kid`, never write hex in widget code.
@immutable
class KidTokens extends ThemeExtension<KidTokens> {
  const KidTokens({
    required this.bg,
    required this.surface,
    required this.ink,
    required this.muted,
    required this.border,
    required this.shadow,
    required this.accentPeach,
    required this.accentPeachTint,
    required this.accentPeachInk,
    required this.accentMint,
    required this.accentMintTint,
    required this.accentMintInk,
    required this.accentSun,
    required this.accentSunTint,
    required this.accentSunInk,
    required this.accentSky,
    required this.accentSkyTint,
    required this.accentSkyInk,
    required this.accentLilac,
    required this.accentLilacTint,
    required this.accentLilacInk,
    required this.accentRose,
    required this.accentRoseTint,
    required this.accentRoseInk,
    required this.accentTeal,
    required this.accentTealTint,
    required this.accentTealInk,
    required this.accentSand,
    required this.accentSandTint,
    required this.accentSandInk,
    required this.onAccent,
    required this.success,
    required this.successTint,
    required this.successInk,
    required this.danger,
    required this.dangerTint,
    required this.dangerInk,
    required this.warning,
    required this.warningTint,
    required this.warningInk,
    required this.focus,
    required this.brandCoral,
    required this.pictoLine,
    required this.pictoMotion,
    required this.pictoDark,
    required this.pictoShine,
    required this.pictoWhite,
    required this.pictoCream,
    required this.pictoRed,
    required this.pictoOrange,
    required this.pictoYellow,
    required this.pictoGreen,
    required this.pictoLeaf,
    required this.pictoBlue,
    required this.pictoWater,
    required this.pictoPurple,
    required this.pictoPink,
    required this.pictoBrown,
    required this.pictoWood,
    required this.pictoSkin,
    required this.pictoGray,
    required this.pictoSteel,
  });

  final Color bg;
  final Color surface;
  final Color ink;
  final Color muted;
  final Color border;
  final Color shadow;
  final Color accentPeach;
  final Color accentPeachTint;
  final Color accentPeachInk;
  final Color accentMint;
  final Color accentMintTint;
  final Color accentMintInk;
  final Color accentSun;
  final Color accentSunTint;
  final Color accentSunInk;
  final Color accentSky;
  final Color accentSkyTint;
  final Color accentSkyInk;
  final Color accentLilac;
  final Color accentLilacTint;
  final Color accentLilacInk;
  final Color accentRose;
  final Color accentRoseTint;
  final Color accentRoseInk;
  final Color accentTeal;
  final Color accentTealTint;
  final Color accentTealInk;
  final Color accentSand;
  final Color accentSandTint;
  final Color accentSandInk;
  final Color onAccent;
  final Color success;
  final Color successTint;
  final Color successInk;
  final Color danger;
  final Color dangerTint;
  final Color dangerInk;
  final Color warning;
  final Color warningTint;
  final Color warningInk;
  final Color focus;
  final Color brandCoral;
  final Color pictoLine;
  final Color pictoMotion;
  final Color pictoDark;
  final Color pictoShine;
  final Color pictoWhite;
  final Color pictoCream;
  final Color pictoRed;
  final Color pictoOrange;
  final Color pictoYellow;
  final Color pictoGreen;
  final Color pictoLeaf;
  final Color pictoBlue;
  final Color pictoWater;
  final Color pictoPurple;
  final Color pictoPink;
  final Color pictoBrown;
  final Color pictoWood;
  final Color pictoSkin;
  final Color pictoGray;
  final Color pictoSteel;

  static const KidTokens light = KidTokens(
    bg: Color(0xFFF9F6F1),
    surface: Color(0xFFFFFFFF),
    ink: Color(0xFF1B203C),
    muted: Color(0xFF606876),
    border: Color(0xFFE0E2EB),
    shadow: Color(0xFF151A32),
    accentPeach: Color(0xFFFC895F),
    accentPeachTint: Color(0xFFFFE6DB),
    accentPeachInk: Color(0xFF842F15),
    accentMint: Color(0xFF54C993),
    accentMintTint: Color(0xFFDBF5E8),
    accentMintInk: Color(0xFF115F40),
    accentSun: Color(0xFFFFC933),
    accentSunTint: Color(0xFFFFF2C7),
    accentSunInk: Color(0xFF7B460A),
    accentSky: Color(0xFF56B3F0),
    accentSkyTint: Color(0xFFDDF0FD),
    accentSkyInk: Color(0xFF134D86),
    accentLilac: Color(0xFFAA8DEC),
    accentLilacTint: Color(0xFFEEE8FC),
    accentLilacInk: Color(0xFF4C2E8A),
    accentRose: Color(0xFFF27DA0),
    accentRoseTint: Color(0xFFFDE2EA),
    accentRoseInk: Color(0xFF8C2145),
    accentTeal: Color(0xFF36BFBA),
    accentTealTint: Color(0xFFD7F4F3),
    accentTealInk: Color(0xFF0A595C),
    accentSand: Color(0xFFD2AE7F),
    accentSandTint: Color(0xFFF5EBDB),
    accentSandInk: Color(0xFF684527),
    onAccent: Color(0xFF151A32),
    success: Color(0xFF259D59),
    successTint: Color(0xFFDAF6E6),
    successInk: Color(0xFF0F5C33),
    danger: Color(0xFFE22834),
    dangerTint: Color(0xFFFFE5E7),
    dangerInk: Color(0xFF931A22),
    warning: Color(0xFFC66C06),
    warningTint: Color(0xFFFFF3D1),
    warningInk: Color(0xFF7B3F0A),
    focus: Color(0xFF1952F0),
    brandCoral: Color(0xFFE76B55),
    pictoLine: Color(0xFF1C223F),
    pictoMotion: Color(0xFF1C223F),
    pictoDark: Color(0xFF343951),
    pictoShine: Color(0xFFFFFFFF),
    pictoWhite: Color(0xFFFFFFFF),
    pictoCream: Color(0xFFFAF3E5),
    pictoRed: Color(0xFFEF584D),
    pictoOrange: Color(0xFFFB8537),
    pictoYellow: Color(0xFFFFCC33),
    pictoGreen: Color(0xFF53C662),
    pictoLeaf: Color(0xFF30915A),
    pictoBlue: Color(0xFF4B93F1),
    pictoWater: Color(0xFF80D5FA),
    pictoPurple: Color(0xFF9F79E2),
    pictoPink: Color(0xFFF896B6),
    pictoBrown: Color(0xFFA4663D),
    pictoWood: Color(0xFFE7B174),
    pictoSkin: Color(0xFFF6CAAC),
    pictoGray: Color(0xFFCACFD8),
    pictoSteel: Color(0xFF8790A1),
  );

  static const KidTokens dark = KidTokens(
    bg: Color(0xFF10121E),
    surface: Color(0xFF181B2A),
    ink: Color(0xFFF2EEE9),
    muted: Color(0xFFA5ABB6),
    border: Color(0xFF2D3143),
    shadow: Color(0xFF04050B),
    accentPeach: Color(0xFFF58C66),
    accentPeachTint: Color(0xFF472C24),
    accentPeachInk: Color(0xFFFFCDB8),
    accentMint: Color(0xFF63C597),
    accentMintTint: Color(0xFF223A2F),
    accentMintInk: Color(0xFFB6EDD1),
    accentSun: Color(0xFFF7C845),
    accentSunTint: Color(0xFF3D341F),
    accentSunInk: Color(0xFFFFEAA3),
    accentSky: Color(0xFF65B6EC),
    accentSkyTint: Color(0xFF223544),
    accentSkyInk: Color(0xFFB9E2FD),
    accentLilac: Color(0xFFB29BE9),
    accentLilacTint: Color(0xFF352B4A),
    accentLilacInk: Color(0xFFDCCFFC),
    accentRose: Color(0xFFEE8CA9),
    accentRoseTint: Color(0xFF482832),
    accentRoseInk: Color(0xFFFECDDC),
    accentTeal: Color(0xFF4ABFBB),
    accentTealTint: Color(0xFF1E3838),
    accentTealInk: Color(0xFFADEBE7),
    accentSand: Color(0xFFCAA87D),
    accentSandTint: Color(0xFF3D3429),
    accentSandInk: Color(0xFFF0DDC2),
    onAccent: Color(0xFF0F1324),
    success: Color(0xFF47C27C),
    successTint: Color(0xFF1E382A),
    successInk: Color(0xFFADEBC8),
    danger: Color(0xFFEF616B),
    dangerTint: Color(0xFF442224),
    dangerInk: Color(0xFFFFC2C6),
    warning: Color(0xFFF9B52F),
    warningTint: Color(0xFF3B301C),
    warningInk: Color(0xFFFFE099),
    focus: Color(0xFF66BFFF),
    brandCoral: Color(0xFFE76B55),
    pictoLine: Color(0xFF080B16),
    pictoMotion: Color(0xFFD9CFBF),
    pictoDark: Color(0xFF5A5E72),
    pictoShine: Color(0xFFFFFFFF),
    pictoWhite: Color(0xFFF1ECE4),
    pictoCream: Color(0xFFEAE0CD),
    pictoRed: Color(0xFFE7564B),
    pictoOrange: Color(0xFFF28136),
    pictoYellow: Color(0xFFF6C531),
    pictoGreen: Color(0xFF51B85F),
    pictoLeaf: Color(0xFF3B9160),
    pictoBlue: Color(0xFF5394EA),
    pictoWater: Color(0xFF75CBF0),
    pictoPurple: Color(0xFFA180DB),
    pictoPink: Color(0xFFF093B2),
    pictoBrown: Color(0xFF9D6743),
    pictoWood: Color(0xFFDAA76C),
    pictoSkin: Color(0xFFECBFA2),
    pictoGray: Color(0xFFB5BAC5),
    pictoSteel: Color(0xFF848B9A),
  );

  /// The 8 member-colour names, in wall order.
  static const List<String> accentNames = <String>[
    'peach',
    'mint',
    'sun',
    'sky',
    'lilac',
    'rose',
    'teal',
    'sand',
  ];

  /// Resolves a member colour name; unknown or null falls back to sky,
  /// matching `AccentPalette.fallback`.
  KidAccent accent(String? name) {
    switch (name?.toLowerCase()) {
      case 'peach':
        return KidAccent(
          base: accentPeach,
          tint: accentPeachTint,
          ink: accentPeachInk,
        );
      case 'mint':
        return KidAccent(
          base: accentMint,
          tint: accentMintTint,
          ink: accentMintInk,
        );
      case 'sun':
        return KidAccent(
          base: accentSun,
          tint: accentSunTint,
          ink: accentSunInk,
        );
      case 'lilac':
        return KidAccent(
          base: accentLilac,
          tint: accentLilacTint,
          ink: accentLilacInk,
        );
      case 'rose':
        return KidAccent(
          base: accentRose,
          tint: accentRoseTint,
          ink: accentRoseInk,
        );
      case 'teal':
        return KidAccent(
          base: accentTeal,
          tint: accentTealTint,
          ink: accentTealInk,
        );
      case 'sand':
        return KidAccent(
          base: accentSand,
          tint: accentSandTint,
          ink: accentSandInk,
        );
      default:
        return KidAccent(
          base: accentSky,
          tint: accentSkyTint,
          ink: accentSkyInk,
        );
    }
  }

  /// Every token keyed by its `tokens.json` name (`accent-peach-tint`).
  Map<String, Color> asMap() => <String, Color>{
    'bg': bg,
    'surface': surface,
    'ink': ink,
    'muted': muted,
    'border': border,
    'shadow': shadow,
    'accent-peach': accentPeach,
    'accent-peach-tint': accentPeachTint,
    'accent-peach-ink': accentPeachInk,
    'accent-mint': accentMint,
    'accent-mint-tint': accentMintTint,
    'accent-mint-ink': accentMintInk,
    'accent-sun': accentSun,
    'accent-sun-tint': accentSunTint,
    'accent-sun-ink': accentSunInk,
    'accent-sky': accentSky,
    'accent-sky-tint': accentSkyTint,
    'accent-sky-ink': accentSkyInk,
    'accent-lilac': accentLilac,
    'accent-lilac-tint': accentLilacTint,
    'accent-lilac-ink': accentLilacInk,
    'accent-rose': accentRose,
    'accent-rose-tint': accentRoseTint,
    'accent-rose-ink': accentRoseInk,
    'accent-teal': accentTeal,
    'accent-teal-tint': accentTealTint,
    'accent-teal-ink': accentTealInk,
    'accent-sand': accentSand,
    'accent-sand-tint': accentSandTint,
    'accent-sand-ink': accentSandInk,
    'on-accent': onAccent,
    'success': success,
    'success-tint': successTint,
    'success-ink': successInk,
    'danger': danger,
    'danger-tint': dangerTint,
    'danger-ink': dangerInk,
    'warning': warning,
    'warning-tint': warningTint,
    'warning-ink': warningInk,
    'focus': focus,
    'brand-coral': brandCoral,
    'picto-line': pictoLine,
    'picto-motion': pictoMotion,
    'picto-dark': pictoDark,
    'picto-shine': pictoShine,
    'picto-white': pictoWhite,
    'picto-cream': pictoCream,
    'picto-red': pictoRed,
    'picto-orange': pictoOrange,
    'picto-yellow': pictoYellow,
    'picto-green': pictoGreen,
    'picto-leaf': pictoLeaf,
    'picto-blue': pictoBlue,
    'picto-water': pictoWater,
    'picto-purple': pictoPurple,
    'picto-pink': pictoPink,
    'picto-brown': pictoBrown,
    'picto-wood': pictoWood,
    'picto-skin': pictoSkin,
    'picto-gray': pictoGray,
    'picto-steel': pictoSteel,
  };

  @override
  KidTokens copyWith({
    Color? bg,
    Color? surface,
    Color? ink,
    Color? muted,
    Color? border,
    Color? shadow,
    Color? accentPeach,
    Color? accentPeachTint,
    Color? accentPeachInk,
    Color? accentMint,
    Color? accentMintTint,
    Color? accentMintInk,
    Color? accentSun,
    Color? accentSunTint,
    Color? accentSunInk,
    Color? accentSky,
    Color? accentSkyTint,
    Color? accentSkyInk,
    Color? accentLilac,
    Color? accentLilacTint,
    Color? accentLilacInk,
    Color? accentRose,
    Color? accentRoseTint,
    Color? accentRoseInk,
    Color? accentTeal,
    Color? accentTealTint,
    Color? accentTealInk,
    Color? accentSand,
    Color? accentSandTint,
    Color? accentSandInk,
    Color? onAccent,
    Color? success,
    Color? successTint,
    Color? successInk,
    Color? danger,
    Color? dangerTint,
    Color? dangerInk,
    Color? warning,
    Color? warningTint,
    Color? warningInk,
    Color? focus,
    Color? brandCoral,
    Color? pictoLine,
    Color? pictoMotion,
    Color? pictoDark,
    Color? pictoShine,
    Color? pictoWhite,
    Color? pictoCream,
    Color? pictoRed,
    Color? pictoOrange,
    Color? pictoYellow,
    Color? pictoGreen,
    Color? pictoLeaf,
    Color? pictoBlue,
    Color? pictoWater,
    Color? pictoPurple,
    Color? pictoPink,
    Color? pictoBrown,
    Color? pictoWood,
    Color? pictoSkin,
    Color? pictoGray,
    Color? pictoSteel,
  }) {
    return KidTokens(
      bg: bg ?? this.bg,
      surface: surface ?? this.surface,
      ink: ink ?? this.ink,
      muted: muted ?? this.muted,
      border: border ?? this.border,
      shadow: shadow ?? this.shadow,
      accentPeach: accentPeach ?? this.accentPeach,
      accentPeachTint: accentPeachTint ?? this.accentPeachTint,
      accentPeachInk: accentPeachInk ?? this.accentPeachInk,
      accentMint: accentMint ?? this.accentMint,
      accentMintTint: accentMintTint ?? this.accentMintTint,
      accentMintInk: accentMintInk ?? this.accentMintInk,
      accentSun: accentSun ?? this.accentSun,
      accentSunTint: accentSunTint ?? this.accentSunTint,
      accentSunInk: accentSunInk ?? this.accentSunInk,
      accentSky: accentSky ?? this.accentSky,
      accentSkyTint: accentSkyTint ?? this.accentSkyTint,
      accentSkyInk: accentSkyInk ?? this.accentSkyInk,
      accentLilac: accentLilac ?? this.accentLilac,
      accentLilacTint: accentLilacTint ?? this.accentLilacTint,
      accentLilacInk: accentLilacInk ?? this.accentLilacInk,
      accentRose: accentRose ?? this.accentRose,
      accentRoseTint: accentRoseTint ?? this.accentRoseTint,
      accentRoseInk: accentRoseInk ?? this.accentRoseInk,
      accentTeal: accentTeal ?? this.accentTeal,
      accentTealTint: accentTealTint ?? this.accentTealTint,
      accentTealInk: accentTealInk ?? this.accentTealInk,
      accentSand: accentSand ?? this.accentSand,
      accentSandTint: accentSandTint ?? this.accentSandTint,
      accentSandInk: accentSandInk ?? this.accentSandInk,
      onAccent: onAccent ?? this.onAccent,
      success: success ?? this.success,
      successTint: successTint ?? this.successTint,
      successInk: successInk ?? this.successInk,
      danger: danger ?? this.danger,
      dangerTint: dangerTint ?? this.dangerTint,
      dangerInk: dangerInk ?? this.dangerInk,
      warning: warning ?? this.warning,
      warningTint: warningTint ?? this.warningTint,
      warningInk: warningInk ?? this.warningInk,
      focus: focus ?? this.focus,
      brandCoral: brandCoral ?? this.brandCoral,
      pictoLine: pictoLine ?? this.pictoLine,
      pictoMotion: pictoMotion ?? this.pictoMotion,
      pictoDark: pictoDark ?? this.pictoDark,
      pictoShine: pictoShine ?? this.pictoShine,
      pictoWhite: pictoWhite ?? this.pictoWhite,
      pictoCream: pictoCream ?? this.pictoCream,
      pictoRed: pictoRed ?? this.pictoRed,
      pictoOrange: pictoOrange ?? this.pictoOrange,
      pictoYellow: pictoYellow ?? this.pictoYellow,
      pictoGreen: pictoGreen ?? this.pictoGreen,
      pictoLeaf: pictoLeaf ?? this.pictoLeaf,
      pictoBlue: pictoBlue ?? this.pictoBlue,
      pictoWater: pictoWater ?? this.pictoWater,
      pictoPurple: pictoPurple ?? this.pictoPurple,
      pictoPink: pictoPink ?? this.pictoPink,
      pictoBrown: pictoBrown ?? this.pictoBrown,
      pictoWood: pictoWood ?? this.pictoWood,
      pictoSkin: pictoSkin ?? this.pictoSkin,
      pictoGray: pictoGray ?? this.pictoGray,
      pictoSteel: pictoSteel ?? this.pictoSteel,
    );
  }

  @override
  KidTokens lerp(ThemeExtension<KidTokens>? other, double t) {
    if (other is! KidTokens) {
      return this;
    }
    return KidTokens(
      bg: Color.lerp(bg, other.bg, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      ink: Color.lerp(ink, other.ink, t)!,
      muted: Color.lerp(muted, other.muted, t)!,
      border: Color.lerp(border, other.border, t)!,
      shadow: Color.lerp(shadow, other.shadow, t)!,
      accentPeach: Color.lerp(accentPeach, other.accentPeach, t)!,
      accentPeachTint: Color.lerp(accentPeachTint, other.accentPeachTint, t)!,
      accentPeachInk: Color.lerp(accentPeachInk, other.accentPeachInk, t)!,
      accentMint: Color.lerp(accentMint, other.accentMint, t)!,
      accentMintTint: Color.lerp(accentMintTint, other.accentMintTint, t)!,
      accentMintInk: Color.lerp(accentMintInk, other.accentMintInk, t)!,
      accentSun: Color.lerp(accentSun, other.accentSun, t)!,
      accentSunTint: Color.lerp(accentSunTint, other.accentSunTint, t)!,
      accentSunInk: Color.lerp(accentSunInk, other.accentSunInk, t)!,
      accentSky: Color.lerp(accentSky, other.accentSky, t)!,
      accentSkyTint: Color.lerp(accentSkyTint, other.accentSkyTint, t)!,
      accentSkyInk: Color.lerp(accentSkyInk, other.accentSkyInk, t)!,
      accentLilac: Color.lerp(accentLilac, other.accentLilac, t)!,
      accentLilacTint: Color.lerp(accentLilacTint, other.accentLilacTint, t)!,
      accentLilacInk: Color.lerp(accentLilacInk, other.accentLilacInk, t)!,
      accentRose: Color.lerp(accentRose, other.accentRose, t)!,
      accentRoseTint: Color.lerp(accentRoseTint, other.accentRoseTint, t)!,
      accentRoseInk: Color.lerp(accentRoseInk, other.accentRoseInk, t)!,
      accentTeal: Color.lerp(accentTeal, other.accentTeal, t)!,
      accentTealTint: Color.lerp(accentTealTint, other.accentTealTint, t)!,
      accentTealInk: Color.lerp(accentTealInk, other.accentTealInk, t)!,
      accentSand: Color.lerp(accentSand, other.accentSand, t)!,
      accentSandTint: Color.lerp(accentSandTint, other.accentSandTint, t)!,
      accentSandInk: Color.lerp(accentSandInk, other.accentSandInk, t)!,
      onAccent: Color.lerp(onAccent, other.onAccent, t)!,
      success: Color.lerp(success, other.success, t)!,
      successTint: Color.lerp(successTint, other.successTint, t)!,
      successInk: Color.lerp(successInk, other.successInk, t)!,
      danger: Color.lerp(danger, other.danger, t)!,
      dangerTint: Color.lerp(dangerTint, other.dangerTint, t)!,
      dangerInk: Color.lerp(dangerInk, other.dangerInk, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      warningTint: Color.lerp(warningTint, other.warningTint, t)!,
      warningInk: Color.lerp(warningInk, other.warningInk, t)!,
      focus: Color.lerp(focus, other.focus, t)!,
      brandCoral: Color.lerp(brandCoral, other.brandCoral, t)!,
      pictoLine: Color.lerp(pictoLine, other.pictoLine, t)!,
      pictoMotion: Color.lerp(pictoMotion, other.pictoMotion, t)!,
      pictoDark: Color.lerp(pictoDark, other.pictoDark, t)!,
      pictoShine: Color.lerp(pictoShine, other.pictoShine, t)!,
      pictoWhite: Color.lerp(pictoWhite, other.pictoWhite, t)!,
      pictoCream: Color.lerp(pictoCream, other.pictoCream, t)!,
      pictoRed: Color.lerp(pictoRed, other.pictoRed, t)!,
      pictoOrange: Color.lerp(pictoOrange, other.pictoOrange, t)!,
      pictoYellow: Color.lerp(pictoYellow, other.pictoYellow, t)!,
      pictoGreen: Color.lerp(pictoGreen, other.pictoGreen, t)!,
      pictoLeaf: Color.lerp(pictoLeaf, other.pictoLeaf, t)!,
      pictoBlue: Color.lerp(pictoBlue, other.pictoBlue, t)!,
      pictoWater: Color.lerp(pictoWater, other.pictoWater, t)!,
      pictoPurple: Color.lerp(pictoPurple, other.pictoPurple, t)!,
      pictoPink: Color.lerp(pictoPink, other.pictoPink, t)!,
      pictoBrown: Color.lerp(pictoBrown, other.pictoBrown, t)!,
      pictoWood: Color.lerp(pictoWood, other.pictoWood, t)!,
      pictoSkin: Color.lerp(pictoSkin, other.pictoSkin, t)!,
      pictoGray: Color.lerp(pictoGray, other.pictoGray, t)!,
      pictoSteel: Color.lerp(pictoSteel, other.pictoSteel, t)!,
    );
  }
}
