// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by tool/sync_kids_assets.dart from the wall handoff.
// Re-run: dart run tool/sync_kids_assets.dart

// ignore_for_file: lines_longer_than_80_chars

/// Motif categories (R3.2): task cards show only `task`, events only `event`.
enum PictoCategory { task, nav, time, feedback, event }

/// One motif of the wall's picto registry.
class PictoMeta {
  const PictoMeta({
    required this.name,
    required this.category,
    required this.emoji,
    required this.labels,
  });

  /// Kebab-case motif name, also the SVG file name.
  final String name;
  final PictoCategory category;

  /// Canonical emoji stored in `Chore.icon` (R3.3).
  final String emoji;

  /// Localised label by language code (de, en, fr, it).
  final Map<String, String> labels;
}

const Map<String, PictoMeta> kPictoCatalog = <String, PictoMeta>{
  'water': PictoMeta(
    name: 'water',
    category: PictoCategory.task,
    emoji: '💧',
    labels: <String, String>{
      'de': 'Wasser trinken',
      'en': 'Drink water',
      'fr': 'Boire de l\'eau',
      'it': 'Bere acqua',
    },
  ),
  'teeth': PictoMeta(
    name: 'teeth',
    category: PictoCategory.task,
    emoji: '🪥',
    labels: <String, String>{
      'de': 'Zähne putzen',
      'en': 'Brush teeth',
      'fr': 'Se brosser les dents',
      'it': 'Lavare i denti',
    },
  ),
  'tidy-toys': PictoMeta(
    name: 'tidy-toys',
    category: PictoCategory.task,
    emoji: '🧸',
    labels: <String, String>{
      'de': 'Spielsachen aufräumen',
      'en': 'Tidy up toys',
      'fr': 'Ranger les jouets',
      'it': 'Mettere via i giochi',
    },
  ),
  'get-dressed': PictoMeta(
    name: 'get-dressed',
    category: PictoCategory.task,
    emoji: '👕',
    labels: <String, String>{
      'de': 'Anziehen',
      'en': 'Get dressed',
      'fr': 'S\'habiller',
      'it': 'Vestirsi',
    },
  ),
  'make-bed': PictoMeta(
    name: 'make-bed',
    category: PictoCategory.task,
    emoji: '🛏️',
    labels: <String, String>{
      'de': 'Bett machen',
      'en': 'Make the bed',
      'fr': 'Faire son lit',
      'it': 'Rifare il letto',
    },
  ),
  'set-table': PictoMeta(
    name: 'set-table',
    category: PictoCategory.task,
    emoji: '🍽️',
    labels: <String, String>{
      'de': 'Tisch decken',
      'en': 'Set the table',
      'fr': 'Mettre la table',
      'it': 'Apparecchiare',
    },
  ),
  'feed-dog': PictoMeta(
    name: 'feed-dog',
    category: PictoCategory.task,
    emoji: '🐶',
    labels: <String, String>{
      'de': 'Hund füttern',
      'en': 'Feed the dog',
      'fr': 'Nourrir le chien',
      'it': 'Dare da mangiare al cane',
    },
  ),
  'feed-cat': PictoMeta(
    name: 'feed-cat',
    category: PictoCategory.task,
    emoji: '🐱',
    labels: <String, String>{
      'de': 'Katze füttern',
      'en': 'Feed the cat',
      'fr': 'Nourrir le chat',
      'it': 'Dare da mangiare al gatto',
    },
  ),
  'trash': PictoMeta(
    name: 'trash',
    category: PictoCategory.task,
    emoji: '🚮',
    labels: <String, String>{
      'de': 'Müll rausbringen',
      'en': 'Take out the trash',
      'fr': 'Sortir la poubelle',
      'it': 'Portare fuori la spazzatura',
    },
  ),
  'water-plants': PictoMeta(
    name: 'water-plants',
    category: PictoCategory.task,
    emoji: '🌱',
    labels: <String, String>{
      'de': 'Pflanzen giessen',
      'en': 'Water the plants',
      'fr': 'Arroser les plantes',
      'it': 'Annaffiare le piante',
    },
  ),
  'homework': PictoMeta(
    name: 'homework',
    category: PictoCategory.task,
    emoji: '✏️',
    labels: <String, String>{
      'de': 'Hausaufgaben',
      'en': 'Homework',
      'fr': 'Devoirs',
      'it': 'Compiti',
    },
  ),
  'read': PictoMeta(
    name: 'read',
    category: PictoCategory.task,
    emoji: '📖',
    labels: <String, String>{
      'de': 'Lesen',
      'en': 'Read',
      'fr': 'Lire',
      'it': 'Leggere',
    },
  ),
  'laundry': PictoMeta(
    name: 'laundry',
    category: PictoCategory.task,
    emoji: '🧺',
    labels: <String, String>{
      'de': 'Wäsche zusammenlegen',
      'en': 'Fold the laundry',
      'fr': 'Plier le linge',
      'it': 'Piegare il bucato',
    },
  ),
  'wash-clothes': PictoMeta(
    name: 'wash-clothes',
    category: PictoCategory.task,
    emoji: '🫧',
    labels: <String, String>{
      'de': 'Wäsche waschen',
      'en': 'Do the washing',
      'fr': 'Faire la lessive',
      'it': 'Fare il bucato',
    },
  ),
  'dishes': PictoMeta(
    name: 'dishes',
    category: PictoCategory.task,
    emoji: '🧽',
    labels: <String, String>{
      'de': 'Abwaschen',
      'en': 'Do the dishes',
      'fr': 'Faire la vaisselle',
      'it': 'Lavare i piatti',
    },
  ),
  'wash-hands': PictoMeta(
    name: 'wash-hands',
    category: PictoCategory.task,
    emoji: '🧼',
    labels: <String, String>{
      'de': 'Hände waschen',
      'en': 'Wash hands',
      'fr': 'Se laver les mains',
      'it': 'Lavarsi le mani',
    },
  ),
  'bath': PictoMeta(
    name: 'bath',
    category: PictoCategory.task,
    emoji: '🛁',
    labels: <String, String>{
      'de': 'Baden',
      'en': 'Bath time',
      'fr': 'Le bain',
      'it': 'Bagnetto',
    },
  ),
  'pajamas': PictoMeta(
    name: 'pajamas',
    category: PictoCategory.task,
    emoji: '🛌',
    labels: <String, String>{
      'de': 'Pyjama anziehen',
      'en': 'Put on pyjamas',
      'fr': 'Mettre son pyjama',
      'it': 'Mettere il pigiama',
    },
  ),
  'backpack': PictoMeta(
    name: 'backpack',
    category: PictoCategory.task,
    emoji: '🎒',
    labels: <String, String>{
      'de': 'Schultasche packen',
      'en': 'Pack school bag',
      'fr': 'Préparer le cartable',
      'it': 'Preparare lo zaino',
    },
  ),
  'sweep': PictoMeta(
    name: 'sweep',
    category: PictoCategory.task,
    emoji: '🧹',
    labels: <String, String>{
      'de': 'Boden wischen',
      'en': 'Sweep the floor',
      'fr': 'Balayer',
      'it': 'Spazzare',
    },
  ),
  'vacuum': PictoMeta(
    name: 'vacuum',
    category: PictoCategory.task,
    emoji: '🌪️',
    labels: <String, String>{
      'de': 'Staubsaugen',
      'en': 'Vacuum',
      'fr': 'Passer l\'aspirateur',
      'it': 'Passare l\'aspirapolvere',
    },
  ),
  'breakfast': PictoMeta(
    name: 'breakfast',
    category: PictoCategory.task,
    emoji: '🥣',
    labels: <String, String>{
      'de': 'Essen',
      'en': 'Eat',
      'fr': 'Manger',
      'it': 'Mangiare',
    },
  ),
  'medicine': PictoMeta(
    name: 'medicine',
    category: PictoCategory.task,
    emoji: '💊',
    labels: <String, String>{
      'de': 'Medizin nehmen',
      'en': 'Take medicine',
      'fr': 'Prendre le médicament',
      'it': 'Prendere la medicina',
    },
  ),
  'music': PictoMeta(
    name: 'music',
    category: PictoCategory.task,
    emoji: '🎹',
    labels: <String, String>{
      'de': 'Instrument üben',
      'en': 'Practise music',
      'fr': 'Faire de la musique',
      'it': 'Esercitarsi con lo strumento',
    },
  ),
  'tidy-room': PictoMeta(
    name: 'tidy-room',
    category: PictoCategory.task,
    emoji: '🗄️',
    labels: <String, String>{
      'de': 'Zimmer aufräumen',
      'en': 'Tidy your room',
      'fr': 'Ranger sa chambre',
      'it': 'Riordinare la camera',
    },
  ),
  'shoes': PictoMeta(
    name: 'shoes',
    category: PictoCategory.task,
    emoji: '👟',
    labels: <String, String>{
      'de': 'Schuhe wegräumen',
      'en': 'Put shoes away',
      'fr': 'Ranger les chaussures',
      'it': 'Mettere via le scarpe',
    },
  ),
  'shopping': PictoMeta(
    name: 'shopping',
    category: PictoCategory.task,
    emoji: '🛒',
    labels: <String, String>{
      'de': 'Einkaufen',
      'en': 'Shopping',
      'fr': 'Faire les courses',
      'it': 'Fare la spesa',
    },
  ),
  'nav-home': PictoMeta(
    name: 'nav-home',
    category: PictoCategory.nav,
    emoji: '🏠',
    labels: <String, String>{
      'de': 'Startseite',
      'en': 'Home',
      'fr': 'Accueil',
      'it': 'Home',
    },
  ),
  'nav-calendar': PictoMeta(
    name: 'nav-calendar',
    category: PictoCategory.nav,
    emoji: '📅',
    labels: <String, String>{
      'de': 'Kalender',
      'en': 'Calendar',
      'fr': 'Calendrier',
      'it': 'Calendario',
    },
  ),
  'nav-meals': PictoMeta(
    name: 'nav-meals',
    category: PictoCategory.nav,
    emoji: '🍴',
    labels: <String, String>{
      'de': 'Mahlzeiten',
      'en': 'Meals',
      'fr': 'Repas',
      'it': 'Pasti',
    },
  ),
  'nav-tasks': PictoMeta(
    name: 'nav-tasks',
    category: PictoCategory.nav,
    emoji: '✅',
    labels: <String, String>{
      'de': 'Aufgaben',
      'en': 'Chores',
      'fr': 'Tâches',
      'it': 'Faccende',
    },
  ),
  'nav-todos': PictoMeta(
    name: 'nav-todos',
    category: PictoCategory.nav,
    emoji: '📋',
    labels: <String, String>{
      'de': 'To-dos',
      'en': 'To-dos',
      'fr': 'À faire',
      'it': 'Da fare',
    },
  ),
  'nav-notes': PictoMeta(
    name: 'nav-notes',
    category: PictoCategory.nav,
    emoji: '🗒️',
    labels: <String, String>{
      'de': 'Notizen',
      'en': 'Notes',
      'fr': 'Notes',
      'it': 'Note',
    },
  ),
  'nav-photos': PictoMeta(
    name: 'nav-photos',
    category: PictoCategory.nav,
    emoji: '🖼️',
    labels: <String, String>{
      'de': 'Fotos',
      'en': 'Photos',
      'fr': 'Photos',
      'it': 'Foto',
    },
  ),
  'nav-settings': PictoMeta(
    name: 'nav-settings',
    category: PictoCategory.nav,
    emoji: '⚙️',
    labels: <String, String>{
      'de': 'Einstellungen',
      'en': 'Settings',
      'fr': 'Paramètres',
      'it': 'Impostazioni',
    },
  ),
  'nav-more': PictoMeta(
    name: 'nav-more',
    category: PictoCategory.nav,
    emoji: '🔲',
    labels: <String, String>{
      'de': 'Mehr',
      'en': 'More',
      'fr': 'Plus',
      'it': 'Altro',
    },
  ),
  'tod-morning': PictoMeta(
    name: 'tod-morning',
    category: PictoCategory.time,
    emoji: '🌅',
    labels: <String, String>{
      'de': 'Morgens',
      'en': 'Morning',
      'fr': 'Matin',
      'it': 'Mattina',
    },
  ),
  'tod-day': PictoMeta(
    name: 'tod-day',
    category: PictoCategory.time,
    emoji: '☀️',
    labels: <String, String>{
      'de': 'Tagsüber',
      'en': 'Daytime',
      'fr': 'Journée',
      'it': 'Giorno',
    },
  ),
  'tod-evening': PictoMeta(
    name: 'tod-evening',
    category: PictoCategory.time,
    emoji: '🌙',
    labels: <String, String>{
      'de': 'Abends',
      'en': 'Evening',
      'fr': 'Soir',
      'it': 'Sera',
    },
  ),
  'tod-night': PictoMeta(
    name: 'tod-night',
    category: PictoCategory.time,
    emoji: '🌛',
    labels: <String, String>{
      'de': 'Nacht',
      'en': 'Night',
      'fr': 'Nuit',
      'it': 'Notte',
    },
  ),
  'tod-anytime': PictoMeta(
    name: 'tod-anytime',
    category: PictoCategory.time,
    emoji: '🌗',
    labels: <String, String>{
      'de': 'Jederzeit',
      'en': 'Anytime',
      'fr': 'Quand tu veux',
      'it': 'Quando vuoi',
    },
  ),
  'celebrate': PictoMeta(
    name: 'celebrate',
    category: PictoCategory.feedback,
    emoji: '🏆',
    labels: <String, String>{
      'de': 'Geschafft!',
      'en': 'Well done!',
      'fr': 'Bravo !',
      'it': 'Bravo!',
    },
  ),
  'oops': PictoMeta(
    name: 'oops',
    category: PictoCategory.feedback,
    emoji: '🩹',
    labels: <String, String>{
      'de': 'Hoppla',
      'en': 'Oops',
      'fr': 'Oups',
      'it': 'Ops',
    },
  ),
  'relax': PictoMeta(
    name: 'relax',
    category: PictoCategory.feedback,
    emoji: '🏖️',
    labels: <String, String>{
      'de': 'Alles erledigt',
      'en': 'All done',
      'fr': 'Tout est fait',
      'it': 'Tutto fatto',
    },
  ),
  'star': PictoMeta(
    name: 'star',
    category: PictoCategory.feedback,
    emoji: '⭐',
    labels: <String, String>{
      'de': 'Stern',
      'en': 'Star',
      'fr': 'Étoile',
      'it': 'Stella',
    },
  ),
  'undo': PictoMeta(
    name: 'undo',
    category: PictoCategory.feedback,
    emoji: '↩️',
    labels: <String, String>{
      'de': 'Rückgängig',
      'en': 'Undo',
      'fr': 'Annuler',
      'it': 'Annulla',
    },
  ),
  'next': PictoMeta(
    name: 'next',
    category: PictoCategory.feedback,
    emoji: '👉',
    labels: <String, String>{
      'de': 'Als Nächstes',
      'en': 'Up next',
      'fr': 'Ensuite',
      'it': 'Prossimo',
    },
  ),
  'pause': PictoMeta(
    name: 'pause',
    category: PictoCategory.feedback,
    emoji: '⏳',
    labels: <String, String>{
      'de': 'Später',
      'en': 'Later',
      'fr': 'Plus tard',
      'it': 'Più tardi',
    },
  ),
  'event-school': PictoMeta(
    name: 'event-school',
    category: PictoCategory.event,
    emoji: '🏫',
    labels: <String, String>{
      'de': 'Schule',
      'en': 'School',
      'fr': 'École',
      'it': 'Scuola',
    },
  ),
  'event-kindergarten': PictoMeta(
    name: 'event-kindergarten',
    category: PictoCategory.event,
    emoji: '🖍️',
    labels: <String, String>{
      'de': 'Kindergarten',
      'en': 'Kindergarten',
      'fr': 'École enfantine',
      'it': 'Scuola dell\'infanzia',
    },
  ),
  'event-soccer': PictoMeta(
    name: 'event-soccer',
    category: PictoCategory.event,
    emoji: '⚽',
    labels: <String, String>{
      'de': 'Fussball',
      'en': 'Football',
      'fr': 'Football',
      'it': 'Calcio',
    },
  ),
  'event-swim': PictoMeta(
    name: 'event-swim',
    category: PictoCategory.event,
    emoji: '🏊',
    labels: <String, String>{
      'de': 'Schwimmen',
      'en': 'Swimming',
      'fr': 'Natation',
      'it': 'Nuoto',
    },
  ),
  'event-doctor': PictoMeta(
    name: 'event-doctor',
    category: PictoCategory.event,
    emoji: '🩺',
    labels: <String, String>{
      'de': 'Arzt',
      'en': 'Doctor',
      'fr': 'Médecin',
      'it': 'Medico',
    },
  ),
  'event-birthday': PictoMeta(
    name: 'event-birthday',
    category: PictoCategory.event,
    emoji: '🎂',
    labels: <String, String>{
      'de': 'Geburtstag',
      'en': 'Birthday',
      'fr': 'Anniversaire',
      'it': 'Compleanno',
    },
  ),
  'event-dinner': PictoMeta(
    name: 'event-dinner',
    category: PictoCategory.event,
    emoji: '🍲',
    labels: <String, String>{
      'de': 'Abendessen',
      'en': 'Dinner',
      'fr': 'Repas du soir',
      'it': 'Cena',
    },
  ),
  'event-music': PictoMeta(
    name: 'event-music',
    category: PictoCategory.event,
    emoji: '🎸',
    labels: <String, String>{
      'de': 'Musikstunde',
      'en': 'Music lesson',
      'fr': 'Cours de musique',
      'it': 'Lezione di musica',
    },
  ),
  'event-play': PictoMeta(
    name: 'event-play',
    category: PictoCategory.event,
    emoji: '🪣',
    labels: <String, String>{
      'de': 'Spielen',
      'en': 'Playtime',
      'fr': 'Jouer',
      'it': 'Giocare',
    },
  ),
  'event-trip': PictoMeta(
    name: 'event-trip',
    category: PictoCategory.event,
    emoji: '🚗',
    labels: <String, String>{
      'de': 'Ausflug',
      'en': 'Outing',
      'fr': 'Excursion',
      'it': 'Gita',
    },
  ),
  'event-bike': PictoMeta(
    name: 'event-bike',
    category: PictoCategory.event,
    emoji: '🚲',
    labels: <String, String>{
      'de': 'Velo fahren',
      'en': 'Bike ride',
      'fr': 'Vélo',
      'it': 'Bicicletta',
    },
  ),
};
