/// Keyword table ported 1:1 from `src/components/pictos/suggest.ts`
/// (`KEYWORDS`). Keywords are pre-normalised (lower-case ASCII). Prefixes:
/// `=` exact word, `~` weak. Order matters: it is the tie-break priority.
library;

const List<(String, List<String>)> kPictoKeywords = <(String, List<String>)>[
  (
    'water',
    <String>[
      'wasser trinken',
      'trink',
      '=wasser',
      'wasserglas',
      'drink',
      'water',
      '=eau',
      'boire',
      'verre d eau',
      'bere',
      'acqua',
      'trinke',
      'wasserli',
    ],
  ),
  (
    'teeth',
    <String>[
      'zahn',
      'zahne',
      'zaehne',
      'zahneputzen',
      'zahnbursten',
      'teeth',
      'tooth',
      'brush teeth',
      'dents',
      'brosser les dents',
      'denti',
      'lavare i denti',
      'zahnli',
    ],
  ),
  (
    'tidy-toys',
    <String>[
      'spielzeug',
      'spielsachen',
      'aufraum',
      'legos',
      '=lego',
      'bauklotz',
      'toys',
      'tidy up',
      'clean up',
      'pick up',
      'ranger',
      'jouets',
      'giocattoli',
      'riordin',
      'mettere in ordine',
      'ufruume',
      'ufrume',
      'gspielzug',
      'spielzug',
    ],
  ),
  (
    'pajamas',
    <String>[
      'pyjama anzieh',
      'pijama anzieh',
      'schlafanzug',
      'pyjama alegge',
      'pyjama aalegge',
      'put on pyjamas',
      'put on pajamas',
      'mettre son pyjama',
      'mettre le pyjama',
      'mettere il pigiama',
    ],
  ),
  (
    'get-dressed',
    <String>[
      'anzieh',
      'anziehen',
      'kleid',
      'kleidung',
      'umzieh',
      'jacke',
      'socken anzieh',
      'handschuh',
      'get dressed',
      'dress',
      'clothes',
      'put on',
      'habill',
      'vetements',
      'vestir',
      'vestiti',
      'vestire',
      'alegge',
      'aalegge',
      'chleider',
      'aaziehe',
    ],
  ),
  (
    'make-bed',
    <String>[
      'bett mach',
      'bettmach',
      'bett mache',
      '=bett',
      'betten',
      'bettdecke',
      'bettli',
      'make bed',
      'make the bed',
      'make your bed',
      '=bed',
      'faire le lit',
      'faire son lit',
      '=lit',
      'letto',
      'rifare il letto',
    ],
  ),
  (
    'set-table',
    <String>[
      'tisch deck',
      'tischdeck',
      'tisch decke',
      '=tisch',
      'abraum',
      'tisch abraum',
      'set the table',
      'set table',
      'lay the table',
      'clear the table',
      '=table',
      'mettre la table',
      'mettre le couvert',
      'couvert',
      'debarrasser',
      'apparecchia',
      'sparecchia',
      'tavola',
    ],
  ),
  (
    'feed-dog',
    <String>[
      '=hund',
      'hunde',
      'hundli',
      'hundefutter',
      'gassi',
      '=dog',
      'dogs',
      'puppy',
      'walk the dog',
      'feed the dog',
      'chien',
      'promener le chien',
      '=cane',
      'cagnolino',
      '~tiere futter',
      '~tier futter',
      '~=futter',
      '~futtern',
      '~fuettern',
      '~=futtere',
    ],
  ),
  (
    'feed-cat',
    <String>[
      'katze',
      'katzen',
      '=busi',
      'busi futter',
      'chatz',
      '=mieze',
      '=cat',
      'cats',
      'kitty',
      '=chat',
      'minou',
      'gatto',
      'gatta',
      'micio',
      'fisch futter',
      'fische futter',
    ],
  ),
  (
    'trash',
    <String>[
      'mull',
      'abfall',
      'kehricht',
      'ghuder',
      'grungut',
      'altpapier',
      'karton',
      'recycl',
      'trash',
      'garbage',
      'rubbish',
      '=bin',
      'bins',
      'poubelle',
      'ordures',
      'dechets',
      'spazzatura',
      'immondizia',
      'rifiuti',
      'pattumiera',
    ],
  ),
  (
    'water-plants',
    <String>[
      'pflanz',
      'blume',
      'giess',
      'wassern',
      'garten',
      'plants',
      'water the plants',
      'watering',
      'garden',
      'flowers',
      'arroser',
      'plantes',
      'fleurs',
      'jardin',
      'annaffia',
      'piante',
      'fiori',
      'giardino',
      'giesse',
      'bluemli',
      'pflanze',
    ],
  ),
  (
    'homework',
    <String>[
      'hausaufgab',
      'hausi',
      'ufzgi',
      'hausufgab',
      'lernen',
      'schreib',
      'rechnen',
      'homework',
      'study',
      '=write',
      'writing',
      '=math',
      'devoirs',
      'ecrire',
      'compiti',
      'studia',
      'scrivere',
    ],
  ),
  (
    'read',
    <String>[
      'lesen',
      'vorlesen',
      '=buch',
      'bucher',
      'bilderbuch',
      'geschichte',
      '=read',
      'reading',
      '=book',
      'books',
      'story',
      'stories',
      '=lire',
      '=livre',
      'livres',
      'histoire',
      'legger',
      '=libro',
      'libri',
      'storia',
      '=lase',
      'buech',
      'gschicht',
      'vorlase',
    ],
  ),
  (
    'laundry',
    <String>[
      '=wasche',
      'zusammenleg',
      'wasche versorg',
      '=falten',
      'socken',
      'kleider versorg',
      'zamelege',
      'zammelege',
      '=fold',
      'folding',
      'fold laundry',
      'fold clothes',
      'put away laundry',
      '=linge',
      'plier',
      'ranger le linge',
      'piegare',
      '=panni',
    ],
  ),
  (
    'wash-clothes',
    <String>[
      'wasche wasch',
      '=waschen',
      'waschmaschine',
      'aufhang',
      'wosch',
      '=wasch',
      'wasche mache',
      'laundry',
      'do the washing',
      'washing machine',
      'wash clothes',
      'hang up',
      'lessive',
      'lave linge',
      'etendre',
      'bucato',
      'lavatrice',
      'stendere',
    ],
  ),
  (
    'dishes',
    <String>[
      'abwasch',
      'geschirr',
      'spul',
      'spuelmaschine',
      'abtrock',
      'dishes',
      'dishwasher',
      'wash up',
      'vaisselle',
      'lave vaisselle',
      '=piatti',
      'lavastoviglie',
      'abwasche',
      'gschirr',
      'abtrochne',
    ],
  ),
  (
    'wash-hands',
    <String>[
      'hande wasch',
      'hande',
      'handewasch',
      'handwasch',
      'seife',
      'wash hands',
      'wash your hands',
      'hands',
      '=soap',
      'laver les mains',
      '=mains',
      'savon',
      'lavare le mani',
      '=mani',
      'sapone',
      'hand wasche',
      'hand wasch',
      '=hand',
    ],
  ),
  (
    'bath',
    <String>[
      'baden',
      '=bad',
      'badewanne',
      'dusch',
      'haare wasch',
      'haarwasch',
      '=bath',
      'bathtime',
      'bath time',
      'shower',
      '=bain',
      'douche',
      'bagno',
      'doccia',
      '=bade',
      'badle',
    ],
  ),
  (
    'pajamas',
    <String>[
      'schlaf',
      'ins bett',
      'zu bett',
      'pyjama',
      'pijama',
      'gute nacht',
      'nachtruhe',
      '=sleep',
      'sleeping',
      'bedtime',
      'go to bed',
      'pajama',
      '=nap',
      '=pj',
      'dormir',
      '=coucher',
      'au lit',
      '=dodo',
      'dormire',
      '=nanna',
      'a letto',
      'pigiama',
      'is bett',
      'gueti nacht',
      '=pfuse',
      '=schlafe',
    ],
  ),
  (
    'backpack',
    <String>[
      'schultasche',
      'schulsack',
      'rucksack',
      'ranzen',
      'turnsack',
      'turnbeutel',
      '=thek',
      'backpack',
      'school bag',
      'schoolbag',
      'pack bag',
      'pack your bag',
      'cartable',
      'sac a dos',
      'sac d ecole',
      'zaino',
      'cartella',
    ],
  ),
  (
    'sweep',
    <String>[
      '=wischen',
      'abwisch',
      'aufwisch',
      'boden wisch',
      '=fegen',
      'besen',
      'kehren',
      'sweep',
      'broom',
      '=mop',
      'mopp',
      'balayer',
      '=balai',
      'spazzare',
      '=scopa',
      'wusche',
    ],
  ),
  (
    'vacuum',
    <String>[
      'staubsaug',
      '=saugen',
      '=staub',
      'vacuum',
      'hoover',
      'aspirateur',
      'aspirapolvere',
      'staubsuge',
      '=suge',
    ],
  ),
  (
    'breakfast',
    <String>[
      'fruhstuck',
      'fruehstueck',
      'zmorge',
      'zmittag',
      'zvieri',
      'znuni',
      '=essen',
      'mittagessen',
      'breakfast',
      'lunch',
      '=eat',
      'snack',
      'cereal',
      'petit dej',
      'dejeuner',
      'manger',
      'gouter',
      'colazione',
      'pranzo',
      'mangiare',
      'merenda',
      'muesli',
      'musli',
      'birchermues',
    ],
  ),
  (
    'medicine',
    <String>[
      'medikament',
      'medizin',
      '=medi',
      'tablette',
      'pille',
      'vitamin',
      'tropfen',
      'hustensaft',
      'medicine',
      'medication',
      '=pill',
      'pills',
      'medicament',
      'pilule',
      'medicina',
      'pillola',
      '=gocce',
    ],
  ),
  (
    'music',
    <String>[
      '=uben',
      '=ueben',
      '=uebe',
      '=musik',
      'musizier',
      'instrument',
      'klavier',
      'flote',
      'blockflot',
      'geige',
      'gitarre',
      'trommel',
      '=floti',
      '~practice',
      '~practise',
      'music',
      'piano',
      'flute',
      'violin',
      'guitar',
      'drums',
      'recorder',
      'musique',
      'jouer du',
      'violon',
      'guitare',
      'musica',
      'suonare',
      'flauto',
      'violino',
      'chitarra',
    ],
  ),
  (
    'tidy-room',
    <String>[
      '=zimmer',
      'zimmer aufraum',
      'kinderzimmer',
      'zimmer ufruume',
      'schublade',
      'kommode',
      'schrank',
      'chaschte',
      'tidy room',
      'clean room',
      'clean your room',
      'bedroom',
      'my room',
      'chambre',
      'ranger la chambre',
      '=camera',
      'stanza',
      'cameretta',
      '=amtli',
      'hausarbeit',
      'haushalt',
      '~=chores',
      '~=chore',
    ],
  ),
  (
    'shoes',
    <String>[
      'schuhe',
      '=schuh',
      'schuhe versorg',
      'stiefel',
      'finken',
      'hausschuh',
      '=schue',
      'shoes',
      'sneakers',
      'boots',
      'slippers',
      'chaussures',
      'baskets',
      'chaussons',
      'scarpe',
      'pantofole',
    ],
  ),
  (
    'shopping',
    <String>[
      'einkauf',
      'kaufen',
      'poschte',
      '=posch',
      'migros',
      '=coop',
      '=denner',
      '=aldi',
      '=lidl',
      'supermarkt',
      'shopping',
      'groceries',
      '=shop',
      '=buy',
      'courses',
      'faire les courses',
      'acheter',
      '=spesa',
      'fare la spesa',
      'supermercato',
      'comprare',
    ],
  ),
  (
    'event-school',
    <String>[
      'schule',
      '=schul',
      'unterricht',
      'schulstunde',
      '=schuel',
      'schuelreis',
      'school',
      '=class',
      'classes',
      'ecole',
      '=classe',
      '=cours',
      'scuola',
      'lezione',
    ],
  ),
  (
    'event-kindergarten',
    <String>[
      'kindergarten',
      '=kita',
      'krippe',
      'spielgruppe',
      'chindsgi',
      'chindergarte',
      '=kiga',
      'kindergarden',
      'preschool',
      'nursery',
      'daycare',
      'creche',
      'maternelle',
      'garderie',
      '=asilo',
      'scuola materna',
      '=materna',
      '=nido',
    ],
  ),
  (
    'event-soccer',
    <String>[
      'fussball',
      'tschutte',
      'tschutti',
      '=fuessball',
      'soccer',
      'football',
      '=foot',
      'calcio',
      'futbol',
    ],
  ),
  (
    'event-swim',
    <String>[
      'schwimm',
      'hallenbad',
      'freibad',
      '=badi',
      'badi',
      'seebad',
      '=swim',
      'swimming',
      '=pool',
      'piscine',
      '=nager',
      'natation',
      'nuoto',
      'piscina',
      'nuotare',
    ],
  ),
  (
    'event-doctor',
    <String>[
      'arzt',
      'zahnarzt',
      'kinderarzt',
      'doktor',
      '=praxis',
      'spital',
      'impfung',
      '=dokter',
      'doctor',
      'dentist',
      'checkup',
      'check up',
      'hospital',
      'vaccin',
      'medecin',
      'docteur',
      'dentiste',
      'pediatre',
      'hopital',
      'medico',
      'dottore',
      'dentista',
      'pediatra',
      'ospedale',
      'vaccino',
    ],
  ),
  (
    'event-birthday',
    <String>[
      'geburtstag',
      'geburi',
      'geschenk',
      '=party',
      '=fest',
      '=feier',
      'birthday',
      '=bday',
      '=gift',
      'anniversaire',
      '=fete',
      'cadeau',
      'compleanno',
      '=festa',
      'regalo',
    ],
  ),
  (
    'event-dinner',
    <String>[
      'abendessen',
      'znacht',
      'nachtessen',
      '=grill',
      'grillier',
      '=grillen',
      'restaurant',
      'essen gehen',
      'pizza',
      'dinner',
      'supper',
      '=bbq',
      'barbecue',
      'zmittag',
      'zmorge',
      'mittagessen',
      '=essen',
      'lunch',
      'brunch',
      'fruhstuck',
      '=diner',
      'souper',
      '=cena',
      'ristorante',
      'pizzeria',
    ],
  ),
  (
    'event-music',
    <String>[
      'musikschule',
      'musikstunde',
      'konzert',
      '=chor',
      'chorprob',
      'klavierstund',
      'gitarrenstund',
      'geigenstund',
      'flotenstund',
      'orchester',
      '=chorli',
      'concert',
      'choir',
      'music lesson',
      'piano lesson',
      'guitar lesson',
      'klavier',
      'gitarre',
      'geige',
      'flote',
      'blockflot',
      'trommel',
      '=musik',
      'piano',
      'guitar',
      'violin',
      'violon',
      'guitare',
      'chitarra',
      'chorale',
      'cours de musique',
      'conservatoire',
      'concerto',
      '=coro',
      'lezione di musica',
    ],
  ),
  (
    'event-play',
    <String>[
      'spielen',
      'spielplatz',
      'spieltreff',
      'spielnachmittag',
      'sandkasten',
      '=spile',
      'spieli',
      'sandele',
      '=play',
      'playdate',
      'play date',
      'playground',
      'jouer',
      '=parc',
      'aire de jeux',
      'giocare',
      'parco giochi',
      '=parco',
    ],
  ),
  (
    'event-trip',
    <String>[
      'ausflug',
      'reise',
      'ferien',
      'urlaub',
      'wander',
      '=zoo',
      '=berg',
      '=fahrt',
      'zugfahrt',
      '=trip',
      'outing',
      'excursion',
      'holiday',
      'vacation',
      '=hike',
      'hiking',
      'travel',
      '=sortie',
      'vacances',
      'voyage',
      'randonnee',
      '=gita',
      'vacanze',
      'viaggio',
      'escursion',
      'usflug',
      'reisli',
      '=zolli',
    ],
  ),
  (
    'event-bike',
    <String>[
      '=velo',
      'velofahr',
      'velotour',
      'fahrrad',
      'rad fahr',
      'radfahr',
      'trottinett',
      '=trotti',
      '=bike',
      'bicycle',
      'cycling',
      'scooter',
      '=bici',
      'bicicletta',
    ],
  ),
];
